import * as React from "react";
import { ThemeProvider, CssBaseline, Toolbar } from "@mui/material";
import theme from "../theme"; // Your custom Material-UI theme
import type { Metadata } from "next";
import "./globals.css";
import ResponsiveAppBar from "@/components/ResponsiveAppBar";
import MainWithDrawer from "./MainWithDrawer";
import ClientRoot from "./ClientRoot";

export const metadata: Metadata = {
  title: "Dereoprojects Landing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <ClientRoot>{children}</ClientRoot>
        </ThemeProvider>
      </body>
    </html>
  );
}
